#!/bin/bash
#SBATCH --job-name=alignscore_xsum_noref             # Job name
#SBATCH --nodes=1                               # Run all processes on a single node    
#SBATCH --ntasks=1                              # Run on a single CPU
#SBATCH --mem=40G                               # Total RAM to be used
#SBATCH --cpus-per-task=8                       # Number of CPU cores
#SBATCH --gres=gpu:1                            # Number of GPUs (per node)
#SBATCH -p nlp-dept                                  # Use the gpu partition
#SBATCH -q nlp-pool                                  # Use the gpu partition
#SBATCH --time=5:00:00                         # Specify the time needed for your experiment
#SBATCH --parsable
#SBATCH --nodelist=gpu80-3,gpu80-2
#SBATCH --output=/fsx/homes/Roman.Vashurin@mbzuai.ac.ae/logs/alignscore_noref.log


cd ~/workspace/alignscore_xsum_noref
source activate polygraph
python get_alignscore.py
